platform :ios, '10.3'
inhibit_all_warnings!

target 'ChipWars' do
  use_frameworks!
  
  pod 'RealmSwift'
  pod 'BWWalkthrough'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD'
  pod 'SwiftKeychainWrapper'
  pod 'SideMenu'
end
